name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json generated/tokens/global.json global
      # Create a light theme
      - run: npx token-transformer tokens.json generated/tokens/light.json light
      # Create a dark theme
      - run: npx token-transformer tokens.json generated/tokens/dark.json dark
      # Convert tokens according to Style Dictionary config
      - run: npm run build
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
